[package]
name = "mvp"
version = "0.1.0"
edition = "2021"
description = "MVP Implementation in Rust and Python by HydroRoll-Team"
license = "AGPL-3.0"

[[bin]]
name = "mvp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }